---
db:
  conn_string: "host=localhost port=15432 user=notifier_db dbname=notifier_db sslmode=disable"
  migration_dir: "./sql-migrations"
  migration_table: "migrations"
webapi:
  listen: ":8088"
events:
  channel_name: "new_event_ch"
